-- source/06_jsp/model2ex 프로젝트는 글삭제시 해당글만 삭제
-- source/07_jQuery/model2ex 프로젝트는 글삭제시 답변글들까지 삭제

DROP TABLE MEMO;
CREATE TABLE MEMO(
    ID NUMBER(4) PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    BGROUP NUMBER(4) NOT NULL,
    BSTEP NUMBER(2) NOT NULL,
    BINDENT NUMBER(2) NOT NULL);
DROP SEQUENCE MEMO_SEQ;
CREATE SEQUENCE MEMO_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
-- 더미 데이터
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글1', MEMO_SEQ.CURRVAL, 0, 0);
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글2', MEMO_SEQ.CURRVAL, 0, 0);
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글3', MEMO_SEQ.CURRVAL, 0, 0);
SELECT * FROM MEMO ORDER BY BGROUP DESC, BSTEP;
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글1-1', 1, 1, 1);
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글2-1', 2, 1, 1);
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글3-1', 3, 1, 1);
UPDATE MEMO SET BSTEP = BSTEP+1 WHERE BGROUP=2 AND BSTEP>0;
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글2-2', 2, 1, 1);
UPDATE MEMO SET BSTEP = BSTEP+1 WHERE BGROUP=2 AND BSTEP>0;
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글2-3', 2, 1, 1);
UPDATE MEMO SET BSTEP = BSTEP+1 WHERE BGROUP=2 AND BSTEP>1;
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글2-3-1', 2, 2, 2);
UPDATE MEMO SET BSTEP = BSTEP + 1 WHERE BGROUP=3 AND BSTEP>0;
INSERT INTO rBOARD VALUES (rBOARD_SEQ.NEXTVAL, '글3-2',3, 1, 1);
SELECT * FROM MEMO ORDER BY BGROUP DESC, BSTEP;
SELECT RPAD(SUBSTR(ENAME, 1,2), LENGTH(ENAME), '*') FROM EMP;
SELECT ID, 
    LPAD('└', (BINDENT*2), ' ')||TITLE, BGROUP, BSTEP, BINDENT FROM MEMO ORDER BY BGROUP DESC, BSTEP;
-- 글 2-3을 지울 경우, 글 2-3-1도 삭제 (DTO : ID(8) 글2-3 / 2(BGROUP) / 1(BSTEP) / 1(BINDENT)
SELECT MIN(BSTEP) FROM MEMO WHERE BGROUP=2 AND BSTEP>1 AND BINDENT<=1; -- 결과:3
DELETE FROM MEMO WHERE BGROUP = 2 AND (BSTEP>=1 AND BSTEP<3);
DELETE FROM MEMO WHERE BGROUP = 2 AND (BSTEP>=1 AND 
    BSTEP<(SELECT MIN(BSTEP) FROM MEMO WHERE BGROUP=2 AND BSTEP>1 AND BINDENT<=1));

-- 글1-1을 지울 경우 (DTO : ID(4), 글1-1, 1(BGROUP) / 1(BSTEP)  / 1(BINDENT)
SELECT MIN(BSTEP) FROM MEMO WHERE BGROUP=1 AND BSTEP>1 AND BINDENT<=1; -- 결과:3

DELETE FROM MEMO WHERE BGROUP = 1 AND (BSTEP>=1 AND 
    BSTEP<(SELECT NVL(MIN(BSTEP),9999) FROM MEMO WHERE BGROUP=1 AND BSTEP>1 AND BINDENT<=1)); -- DAO에 들어갈 QUERY(BGROUP, BSTEP, BINDENT가 필요)

-- 글 2번 글 경우 (DTO : ID(2), 글2, 2(BGROUP) / 0(BSTEP) / 0(BINDENT)
DELETE FROM MEMO WHERE BGROUP = 2 AND (BSTEP>=0 AND 
    BSTEP<(SELECT NVL(MIN(BSTEP),9999) FROM MEMO WHERE BGROUP=2 AND BSTEP>0 AND BINDENT<=0));-- DAO에 들어갈 QUERY
--확인용
SELECT ID, 
    LPAD('└', (BINDENT*2), ' ')||TITLE, BGROUP, BSTEP, BINDENT FROM MEMO ORDER BY BGROUP DESC, BSTEP;